colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: /home/eho/.local/share/jrnl/journal.txt
linewrap: 79
tagsymbols: '@'
template: /home/eho/.config/jrnl/template.txt
timeformat: '%Y-%m-%d %H:%M'
version: v2.8.3
