#!/bin/bash
# Set key config for material shell (Gnome 41.2)

#gsettings --schemadir /usr/share/gnome-shell/extensions/material-shell@papyelgringo/schemas set org.gnome.shell.extensions.materialshell.bindings focus-monitor-left "['']"
#gsettings --schemadir /usr/share/gnome-shell/extensions/material-shell@papyelgringo/schemas list-recursively org.gnome.shell.extensions.materialshell.bindings | sort
SCHEMA_DIR="/usr/share/gnome-shell/extensions/material-shell@papyelgringo/schemas"
SETTING_NAME="org.gnome.shell.extensions.materialshell.bindings"
CMD="gsettings --schemadir ${SCHEMA_DIR} set ${SETTING_NAME}"

${CMD} app-launcher "['']"
${CMD} cycle-tiling-layout "['<Super>f']"
${CMD} focus-monitor-down "['']"
${CMD} focus-monitor-up "['']"
${CMD} focus-monitor-left "['<Alt><Super>h']"
${CMD} focus-monitor-right "['<Alt><Super>l']"
${CMD} kill-focused-window "['<Super>q']"
${CMD} last-workspace "['']"
${CMD} move-window-bottom "['<Super>Bottom']"
${CMD} move-window-left "['<Super>Left']"
${CMD} move-window-monitor-down "['<Shift><Super>Down']"
${CMD} move-window-monitor-left "['<Shift><Super>Left']"
${CMD} move-window-monitor-right "['<Shift><Super>Right']"
${CMD} move-window-monitor-up "['<Shift><Super>Up']"
${CMD} move-window-right "['<Super>Right']"
${CMD} move-window-top "['<Super>Up']"
${CMD} move-window-to-workspace-10 "['<Shift><Super>0']"
${CMD} move-window-to-workspace-1 "['<Shift><Super>1']"
${CMD} move-window-to-workspace-2 "['<Shift><Super>2']"
${CMD} move-window-to-workspace-3 "['<Shift><Super>3']"
${CMD} move-window-to-workspace-4 "['<Shift><Super>4']"
${CMD} move-window-to-workspace-5 "['<Shift><Super>5']"
${CMD} move-window-to-workspace-6 "['<Shift><Super>6']"
${CMD} move-window-to-workspace-7 "['<Shift><Super>7']"
${CMD} move-window-to-workspace-8 "['<Shift><Super>8']"
${CMD} move-window-to-workspace-9 "['<Shift><Super>9']"
${CMD} navigate-to-workspace-10 "['<Super>0']"
${CMD} navigate-to-workspace-1 "['<Super>1']"
${CMD} navigate-to-workspace-2 "['<Super>2']"
${CMD} navigate-to-workspace-3 "['<Super>3']"
${CMD} navigate-to-workspace-4 "['<Super>4']"
${CMD} navigate-to-workspace-5 "['<Super>5']"
${CMD} navigate-to-workspace-6 "['<Super>6']"
${CMD} navigate-to-workspace-7 "['<Super>7']"
${CMD} navigate-to-workspace-8 "['<Super>8']"
${CMD} navigate-to-workspace-9 "['<Super>9']"
${CMD} next-window "['<Super>k']"
${CMD} next-workspace "['<Super>l']"
${CMD} previous-window "['<Super>j']"
${CMD} previous-workspace "['<Super>h']"
${CMD} resize-window-down "['<Ctrl><Super>Down']"
${CMD} resize-window-left "['<Ctrl><Super>Left']"
${CMD} resize-window-right "['<Ctrl><Super>Right']"
${CMD} resize-window-up "['<Ctrl><Super>Up']"
${CMD} reverse-cycle-tiling-layout "['<Shift><Super>f']"
${CMD} toggle-material-shell-ui "['<Super>Escape']"
${CMD} use-float-layout "['']"
${CMD} use-grid-layout "['']"
${CMD} use-half-horizontal-layout "['']"
${CMD} use-half-layout "['']"
${CMD} use-half-vertical-layout "['']"
${CMD} use-maximize-layout "['']"
${CMD} use-ratio-layout "['']"
${CMD} use-simple-horizontal-layout "['']"
${CMD} use-simple-layout "['']"
${CMD} use-simple-vertical-layout "['']"
${CMD} use-split-layout "['']"
